### ISSUE TITLE
Komplikation UI-Debian11-SQL

### ISSUE THREAD

**Issue by Nagelow** [Ifi-Softwareentwicklung-SoSe2022/Projekt-Bierzaehler#18]
Leider gibt es ein Problem beim Ausführen des Userinterface, wenn SQL-Kommandos durch Button_click ausgeführt werden sollen. Leider schließt sich, sobald der Button geklickt wurde, das UI. Jedoch funktioniert ein Testprogramm das über dotnet run in der Konsole ausgeführt werden kann. Dieses erreicht auch die auf dem RasPI eingerichteten Datenbank und kann Daten aus dieser ziehen. Heißt es gibt unter Debian 11 eigentlich keine Probleme c# und entsprechende SQL-Befehle auszuführen. Jedoch in Kombination von Windowsforms und SQL-Befehlen schon

**Comment by RiadR555** [comment]
Leider funktioniert es immer noch nicht, deshalb wurde es auf Avalonia umgestellt :(
