### ISSUE TITLE
Datenbanksystem erstellen

### ISSUE THREAD

**Issue by Nagelow** [Ifi-Softwareentwicklung-SoSe2022/Projekt-Bierzaehler#3]
Erstelle ein Datenbanksystem, das die die Informationen die der Raspberry PI übertragen soll, speichert und zusammen rechnet.

**Comment by RiadR555** [comment]
Ich habe in Branche SQL das Datenbanksystem hochgeladen. Bitte es nochmal checken und einen Kommentar hinterlassen, falls du paar Anmerkungen hast :)
